#execution_env=remote	
execution_env=local
appUR1=http://localhost/opencart/upload/
appURL2=https://tutorialsninja.com/demo/
email=utkalikajena0024@gmail.com
password=Ema@0987
#password=Ema@098765
searchProductName=android